### ISSUE TITLE
"This page appears to be missing CSS declarations for Mapbox GL JS"

### ISSUE THREAD

**Issue by gridpatrik** [arnaudleclerc/ng-azure-maps#18]
During page load I'm seeing the following warning in the console "This page appears to be missing CSS declarations for Mapbox GL JS".

Versions...
"azure-maps-control": "^2.0.31",
"azure-maps-drawing-tools": "^0.1.4",
"azure-maps-rest": "^2.0.5",
"ng-azure-maps": "^2.0.3",

**Comment by arnaudleclerc** [comment]
@gridpatrik Could you try to add the following line on the head tag of your index.html ? 

```
<link rel="stylesheet" href="https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.min.css" type="text/css" />
```

That's something I need to add on the readme, you still need to reference the atlas.min.css yourself for now. Let me know if this works for you

**Comment by gridpatrik** [comment]
That solves the problem!
