### ISSUE TITLE
Unable to hide logo, feedback link, copyright

### ISSUE THREAD

**Issue by ganijon** [arnaudleclerc/ng-azure-maps#30]
The azure-map.directive exposes boolean inputs to show/hide MS logo, feedback link. However, when I set values to those, there is no effect.

**Comment by arnaudleclerc** [comment]
Hi @ganijon . Are you referring to the `showFeedbackLink` and `showLogo` inputs ? If so, I have been testing them and they work fine for me. Here is a sample and the result I got : 

```
<azure-map [center]="[11.47, 48.18]" mapStyle='grayscale_dark' [zoom]="10" [showFeedbackLink]="false"
  [showLogo]="false">
</azure-map>
```

![image](https://user-images.githubusercontent.com/9578038/107429118-dd8d8980-6b23-11eb-830d-64e24998b5c0.png)

As far as I know, there is no possibility to hide the copyright. Could you please share an example where it does not work for you ?

**Comment by ganijon** [comment]
Hi @arnaudleclerc. Thanks. I tried it again, it worked! And, as you mentioned, the copyright won't go away.
![image](https://user-images.githubusercontent.com/1889400/107430638-6b9d4c00-6af3-11eb-9541-813126397080.png)
