### ISSUE TITLE
Blank map rendered

### ISSUE THREAD

**Issue by thomashoefkens-vw** [arnaudleclerc/ng-azure-maps#33]
Hi!

I was trying to use ng-azure-maps, but when loading the component, the map renders as a white area.

What could I be doing wrong?

This is my module:

![image](https://user-images.githubusercontent.com/71012278/109316043-7c67f480-784b-11eb-9655-a531f16ff344.png)

And this is my component:

![image](https://user-images.githubusercontent.com/71012278/109316105-91dd1e80-784b-11eb-9495-e4f2d041de37.png)

The resulting page in ng is:

![image](https://user-images.githubusercontent.com/71012278/109316190-a7524880-784b-11eb-8668-7292d8e0ab3d.png)

Thanks very much in advance!
Thomas

**Comment by arnaudleclerc** [comment]
Hi @thomashoefkens-vw ! 

I think you forgot to specify which type of authentication you will be using, the subscription key by itself is not enough. Could you try to replace your call to `AzureMapsModule.forRoot` as follows ? 

```
 AzureMapsModule.forRoot({
      authOptions: {
        authType: AuthenticationType.subscriptionKey,
        subscriptionKey: environment.azureMapsSubscriptionKey,
      }
    })
```

Let me know if that solves your issue !

**Comment by thomashoefkens-vw** [comment]
Hi @arnaudleclerc !

Thank you for the input.
After that change it loads with an unhappy smiley:

![image](https://user-images.githubusercontent.com/71012278/109627590-124c9980-7b42-11eb-91f6-45a96ff59c74.png)

Do you have an idea?

**Comment by thomashoefkens-vw** [comment]
I briefly picked the route sample, was shortly able to see a map being rendered, and afterwards only got this error:
![image](https://user-images.githubusercontent.com/71012278/109628042-943cc280-7b42-11eb-98a2-6bdbea56d5b0.png)
I will try some other samples that you have created.

**Comment by thomashoefkens-vw** [comment]
@arnaudleclerc The map loads fine in Safari... seems to be a Google Chrome / Maps compatibility issue. Thank you!
