### ISSUE TITLE
"Object Unsubscribed" Error On Component Destroy

### ISSUE THREAD

**Issue by profezzional** [arnaudleclerc/ng-azure-maps#34]
When navigating away from a page with the azure-maps component loaded on it, two "object unsubscribed" errors appear in the browser console:
![image](https://user-images.githubusercontent.com/12171532/113162016-e68a0580-920c-11eb-80b8-67e2848b3391.png)
When omitting the maps component, the error doesn't show up. The component works as expected otherwise.

Using Angular 11.1.2 on the latest Chrome version.

**Comment by arnaudleclerc** [comment]
Thanks for pointing it out! I'll fix that, but I probably won't be able to do it until next week. I'll let you when it's done.

**Comment by arnaudleclerc** [comment]
@profezzional This should now be fixed in the version `3.5.2`. Please give it a try and let me know if this works for you. Feel free to reopen this issue if the problem persists.
