### ISSUE TITLE
Azure maps are not responsive

### ISSUE THREAD

**Issue by brij5580** [arnaudleclerc/ng-azure-maps#37]
![azure-map-not-responsive](https://user-images.githubusercontent.com/25244453/124068583-65831a00-da58-11eb-890b-96cb5372f357.PNG)

Azure map is not responsive. It exceeds the div.

**Comment by arnaudleclerc** [comment]
Hi. All the tags you can find in this library are directives, not components. They don't influence how the native azure-maps elements are rendered. I think this is the responsibility of applications using this library to handle the design or the responsiveness of the map.

I am sadly far from being a CSS expert, so I cannot give you any advice on how you can achieve that. But I guess that should be possible on your side, right ?

**Comment by arnaudleclerc** [comment]
I'll close this one as it won't be fixed on the library but should be done on the application using it.
