### ISSUE TITLE
Can't get it to work with Angular 14

### ISSUE THREAD

**Issue by PATTE7556** [arnaudleclerc/ng-azure-maps#62]
Hi!
Can you update this package to use  Angular 14?

**Comment by elgurinn** [comment]
Are there any plans to update the library to support Angular 14?

**Comment by arnaudleclerc** [comment]
Sorry, I have been postponing that for too long. I will try to do it today. I will let you know, when a new version is available

**Comment by arnaudleclerc** [comment]
I just published a v6.0.0 which is compatible with angular 14. I will close this issue, but please take a look at the latest version and feel free to reopen this issue if there is any problem.
